### PR TITLE
fix rails 5 deprecations

### LINKED ISSUE #665: Rails 5 deprecations
```
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from block (3 levels) in <class:Engine> at /Users/connor/.rvm/gems/ruby-2.3.0/gems/turbolinks-2.5.3/lib/turbolinks.rb:14)
DEPRECATION WARNING: after_filter is deprecated and will be removed in Rails 5.1. Use after_action instead. (called from block (3 levels) in <class:Engine> at /Users/connor/.rvm/gems/ruby-2.3.0/gems/turbolinks-2.5.3/lib/turbolinks.rb:15)
```

`before_filter` and `after_filter` should be updated for turbolinks-classic compatibility with Rails 5 :)

### PR DESCRIPTION
**Pull request by ajb**
closes #665

@dhh mentioned (https://github.com/rails/rails/issues/24018#issuecomment-191852988) that the maintainers would be open to releasing a new version of turbolinks-classic that fixes these deprecations, so I humbly submit this PR for review. 😁

### CODE REVIEW

**Comment by nilbus** [comment]
Is this backward-compatible with Rails 4?

**Comment by aried3r** [comment]
> Is this backward-compatible with Rails 4?

Not fully, I think. `Module#prepend` came with [Ruby 2.0](https://www.ruby-lang.org/en/news/2013/02/24/ruby-2-0-0-p0-is-released/) but [Rails 4 supports Ruby 1.9.3](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#ruby-versions).

**Comment by aried3r** [comment]
Ping @rafaelfranca, would you be open to a PR that removes compatibility for Ruby <2, maybe even Rails <4.2?

We cannot yet switch to TL 5 in our project, so we want to keep using TL-classic for the time being.

**Comment by aried3r** [comment]
Nevermind, I saw this is actually fixed in the current master branch: https://github.com/turbolinks/turbolinks-classic/blob/80216ce9d89920bf073709405e3fce6d0a3ccd9a/lib/turbolinks.rb#L13-L20

**Comment by mmoll** [comment]
what's the status here?

**Comment by rafaelfranca** [comment]
I'd prefer to not remove support to Rails 4.2 right now. So can we conditionally check the Rails version where it is necessary?

**Comment by mmoll** [comment]
I can take a look how far I can get, but first #678 would need to get merged.

**Comment by mmoll** [comment]
hrm, I guess that whole testing stuff should go to 2-5-stable, like this PR?

**Comment by mmoll** [comment]
please see #679

**Pull request closed without merging**
