### PR TITLE
fix rails 5 deprecations

### PR DESCRIPTION
**Pull request by xprazak2**
This continues where #671 left off, I tried to get in touch with the original author but I did not hear back from him. I added conditional checks to keep backward compatibility.

### CODE REVIEW

**Comment by xprazak2** [comment]
tests failing due to missing Rakefile in 2-5-stable branch

**Comment by mmoll** [comment]
@rafaelfranca ☝️

**Comment by jhubert** [comment]
@rafaelfranca Any chance of getting this in? We can fork, but this seems really useful to those of us who've yet to upgrade to Turbolinks 5.

**Comment by mmoll** [comment]
could there be a 2.5.4 release on rubygems?

**Comment by jhubert** [comment]
@rafaelfranca Woohoo! Thank you. 💟

**Comment by rafaelfranca** [comment]
Yes of course. I'll release it tomorrow

**Comment by mmoll** [comment]
@rafaelfranca I know I'm annoying, but: any news here?

**Comment by mmoll** [comment]
anybody?

**Comment by rafaelfranca** [comment]
I still didn't had time to release it, but I'll work on it soon. Meanwhile you can always point to github using bundler (this is one of the best features that bundler has)

**Comment by rafaelfranca** [comment]
Oh. It was easier than I thought. It 2.5.4 is released now

**Comment by mmoll** [comment]
@rafaelfranca Thanks a bunch! Because of the way we package our software for nightly RPM/DEB builds it's not easily possible to use git repos in bundler for production builds...

**Pull request merged**
